### ISSUE TITLE
Vorschlag Refactoring

### ISSUE THREAD

**Issue by SimonJpg2** [Henning-git/KITS_Programmieren1_praktikum2#2]
https://github.com/Henning-git/KITS_Programmieren1_praktikum2/blob/2c3df8eaa82f580e954a5ed7eaf66b2c7fbf4593/Aufgabe_10/main.cpp#L151-L190

Hi, ein kurzer Vorschlag, wie ich mit switch cases arbeite, wenn mehrere cases zu einem zusammengefasst werden können. 

Wenn du beispielsweise für zwei chars `i` und `I` die Funktion `add_at_end()` aufrufen möchtest, kannst du das in einem case zusammenfassen:

```
switch(input) {
            case 'i':
            case 'I':
                add_at_end();
                break;
            
            case 's':
            case 'S': 
                print_used_fields();
                break;

            <snip>
}
```
Du kannst deine Lösung auch so stehen lassen, beide Schreibweisen sind richtig :)

**Comment by hprien** [comment]
Danke voll guter Tipp.\
Die Klammern braucht man in diesem Fall tatsächlich nicht. Wenn man Variablen in einem case definieren möchte, sind sie allerdings nötig.
